runtime: nodejs18

env_variables:
  NODE_ENV: production
  DATABASE_URL: $DATABASE_URL
  GOOGLE_CLIENT_ID: $GOOGLE_CLIENT_ID
  IA_URL: $IA_URL
  IA_BASIC_USER_NAME: $IA_BASIC_USER_NAME
  IA_BASIC_USER_PASS: $IA_BASIC_USER_PASS

handlers:
  - url: /.*
    script: auto
