services:
  api:
    depends_on:
      - database
    build:
      dockerfile: Dockerfile
      context: .      
      target: development
    volumes:
      - .:/app
    env_file:
    - .env
    environment:
      - WDS_SOCKET_HOST=127.0.0.1 
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    command: yarn start:dev  
    ports:
      - 3000:3000
  database:
   image: postgres
   restart: always
   environment:
    POSTGRES_DB: ${POSTGRES_DB}
    POSTGRES_USER: ${POSTGRES_USER}
    POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
   ports:
    - '5432:5432'
   volumes:
    - docker-nest-postgres:/var/lib/postgresql/data
volumes:
  docker-nest-postgres: