name: Deploy to AWS EC2 with Docker

on:
  push:
    branches:
      - main
    paths:
      - 'apps/times-api/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Set up node
      uses: actions/setup-node@v4
      with:
        node-version: 18.18.2

    - name: Build Docker image
      run: |
        cd apps/times-api
        docker build --build-arg DATABASE_URL=${{secrets.DATABASE_URL}} \
        --build-arg GOOGLE_CLIENT_ID=${{secrets.GOOGLE_CLIENT_ID}} \
        --build-arg PORT=3000 \
        --build-arg NODE_ENV=production
        -t kartime-api-image . \
       


    - name: Login to AWS ECR (Elastic Container Registry)
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_REGION }}
        aws ecr get-login-password --region ${{ secrets.AWS_REGION }} | docker login --username AWS --password-stdin ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com

    - name: Tag Docker image
      run: docker tag kartime-api-image:latest ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/kartime-api-image:latest

    - name: Push Docker image to ECR
      run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/kartime-api-image:latest

    - name: Deploy to Elastic Beanstalk
      uses: einaregilsson/beanstalk-deploy@v22
      with:
        aws_access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        application_name: "kartime-api"
        environment_name: "Kartime-api-env"
        version_label: "deploy-${{ github.sha }}"
        region: ${{secrets.AWS_REGION}}
        deployment_package: "apps/times-api/Dockerrun.aws.json"
