name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main
    paths:
      - apps/times-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - uses: 73h/gae-app-yaml-replace-env-variables@v0.3
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Move files to kartime-api directory
        run: mv apps/times-api kartime-api

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v0
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to GCP App Engine
        run: gcloud app deploy apps/times-api/app.yaml --project kartime-415323 
