name: Deploy to GCP App Engine

on:
  push:
    branches:
      - main
    paths:
      - apps/times-api

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - uses: 73h/gae-app-yaml-replace-env-variables@v0.3
        env:
          NODE_ENV: production
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          GOOGLE_CLIENT_ID: ${{ secrets.GOOGLE_CLIENT_ID }}
          IA_URL: ${{ secrets.IA_URL }}
          IA_BASIC_USER_NAME: ${{ secrets.IA_BASIC_USER_NAME }}
          IA_BASIC_USER_PASS: ${{ secrets.IA_BASIC_USER_PASS }}
        with:
          app_yaml_path: "apps/times-api/app.yaml"

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18

      - name: Remove monorepo package
        run: rm package.json yarn.lock

      - name: install dependencies
        run: cd apps/times-api && yarn --production

      - name: Authenticate with Google Cloud
        uses: google-github-actions/auth@v2.1.2
        with:
          credentials_json: ${{ secrets.GCP_SA_KEY }}

      - name: Deploy to GCP App Engine
        run: cd apps/times-api && gcloud app deploy --project kartime-415323 
